### ISSUE TITLE
how do I use this?

### ISSUE THREAD

**Issue by ccorcos** [snowcrshd/cyberpunk.vim#1]

**Comment by nick-andren** [comment]
On Linux, you can do the following:

1. Create the directory `~/.vim/colors`
2. Copy the file in this repo and save it under `~/.vim/colors/cyberpunk.vim`
3. In your terminal, open `vim`
4. Type `:colorscheme cyberpunk` and hit enter

**Comment by ccorcos** [comment]
Awesome. thanks!
